linux_build_task:
  container:
    image: gcc:latest
  install_script:
    - apt-get -y update
    - apt-get -y install cmake qt5-default libasound2-dev
  config_script:
    - git submodule update --init --recursive --remote
    - mkdir debug
    - cd debug
    - cmake -D CMAKE_BUILD_TYPE=Debug ..
    - cd ..
    - mkdir release
    - cd release
    - cmake -D CMAKE_BUILD_TYPE=Release ..
    - cd ..
  build_script:
    - cd debug
    - make all
    - cd ..
    - cd release
    - make all
    - cd ..

mac_build_task:
  container:
    image: high-sierra-xcode-9.4.1
  install_script:
    - brew install qt5 || (brew update && brew install qt5)
  config_script:
    - git submodule update --init --recursive --remote
    - mkdir debug
    - cd debug
    - cmake -D CMAKE_BUILD_TYPE=Debug ..
    - cd ..
    - mkdir release
    - cd release
    - cmake -D CMAKE_BUILD_TYPE=Release ..
    - cd ..
  build_script:
    - cd debug
    - make all
    - cd ..
    - cd release
    - make all
    - cd ..
