language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    osx_image: xcode12
    compiler: gcc
    addons:
      homebrew:
        packages:
          - qt5
        update: true
  - os: osx
    osx_image: xcode12
    compiler: clang
    addons:
      homebrew:
        packages:
          - qt5
        update: true

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install qt5-default libasound2-dev; fi

before_script:
  - git submodule update --init --recursive --remote
  - mkdir debug
  - cd debug
  - cmake -D CMAKE_BUILD_TYPE=Debug ..
  - cd ..
  - mkdir release
  - cd release
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - cd ..

script:
  - cd debug
  - make all
  - cd ..
  - cd release
  - make all
  - cd ..
