name: dspatcher
version: "1.0"
summary: Cross-Platform Graphical Tool for DSPatch
description: http://flowbasedprogramming.com

grade: devel
confinement: strict
base: core18

apps:
  dspatcher:
    command: desktop-launch DSPatcher
    environment:
      DSPATCH_PLUGINS: $SNAP/lib/dspatch/components
      DSPATCH_USER_PLUGINS: $SNAP_USER_COMMON
      WAVEREADER_FILE: $SNAP_USER_COMMON/Sample.wav
    plugs:
      - home
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  dspatcher-app:
    after: [desktop-qt5]
    source: .
    plugin: cmake
    build-packages:
      - libpulse-dev
    stage-packages:
      - libpulse0
